media:
  input: public
  output: /

content:
  - name: obras
    label: Obras
    type: collection
    path: src/data/obras
    format: yaml-frontmatter

    fields:
      - { name: title, label: Título, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: year, label: Año, type: number }
      - { name: description, label: Descripción, type: text, required: false }

      - name: status
        label: Estado
        type: select
        options:
          values: [draft, published, archived]
        default: draft

      - { name: cover, label: Imagen principal, type: image }
      - { name: coverAlt, label: Texto alternativo, type: string }

      - name: mediaType
        label: Tipo de media
        type: select
        options:
          values: [image, video, iframe]
        default: image

      - { name: mediaSrc, label: Fuente del media, type: string, required: false }
      - { name: mediaAlt, label: Texto alternativo del media, type: string, required: false }

      - name: bento
        label: Tamaño en grid
        type: select
        options:
          values: [small, wide, tall, large]
        default: small

  - name: about
    label: About
    type: file
    path: src/data/about.md
    format: yaml-frontmatter

    fields:
      - name: title
        label: Título
        type: string

      - name: body
        label: Contenido
        type: rich-text